WeatherApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('weather.urls')),
]

weather/urls.py
from django.urls import path
from . import views

app_name='weather'
urlpatterns = [
    path('', views.index, name='index'),
    path('info/', views.info, name='info'),
    path('documents/', views.documents, name='documents'),
]

weather/models.py
from django.db import models

class City(models.Model):
    name=models.CharField(max_length=30)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name='Город'
        verbose_name_plural='Города'

weather/forms.py
from .models import City
from django.forms import ModelForm, TextInput

class CityForm(ModelForm):
    class Meta:
        model=City
        fields=['name']
        widgets={'name': TextInput(attrs={
            'class': 'form-control',
            'name':'city',
            'id':'city',
            'placeholder':'Введите город'
        })}

weather/views.py
import requests
from django.shortcuts import render
from .models import City
from .forms import CityForm

def index(request):
    appid='7bb22b66e96d4bfba289943498c913e8'
    url='https://api.openweathermap.org/data/2.5/weather?q={}&units=metric&appid=' + appid
    if(request.method=='POST'):
        form=CityForm(request.POST)
        form.save()
    form=CityForm()
    cities=City.objects.all()
    all_cities=[]
    for city in cities:
        res = requests.get(url.format(city.name)).json()
        city_info={
            'city': city.name,
            'temp': res["main"]["temp"],
            'icon': res["weather"][0]["icon"]
        }
        all_cities.append(city_info)
    context={'all_info': all_cities, 'form': form}
    return render(request, 'weather/index.html', context)

def info(request):
    context={}
    return render(request, 'weather/info.html', context)

def documents(request):
    context={}
    return render(request, 'weather/documents.html', context)

weather/templates/weather/documents.html
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Погодное приложение</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
</head>
<body>
    <div class="d-flex flex-column flex-md-row align-items-center pb-2 mb-3 bg-white border-bottom shadow-sm">
      <a href="/" class="d-flex align-items-center link-body-emphasis text-decoration-none">
        <a class="me-3 ms-4 py-3 fs-4 link-body-emphasis text-decoration-none" href="#">Weather☁️</a>
      </a>

      <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
        <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'weather:index' %}">Главная</a>
        <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'weather:info' %}">Информация</a>
        <a class="me-3 btn btn-outline-primary" href="{% url 'weather:documents' %}">Документация</a>
      </nav>
    </div>
    <div>
        <h3>Документация о погоде</h1>
    </div>
</body>
</html>

weather/templates/weather/index.html
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Погодное приложение</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
</head>
<body>
    <div class="d-flex flex-column flex-md-row align-items-center pb-2 mb-3 bg-white border-bottom shadow-sm">
      <a href="/" class="d-flex align-items-center link-body-emphasis text-decoration-none">
        <a class="me-3 ms-4 py-3 fs-4 link-body-emphasis text-decoration-none" href="#">Weather☁️</a>
      </a>

      <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
        <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'weather:index' %}">Главная</a>
        <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'weather:info' %}">Информация</a>
        <a class="me-3 btn btn-outline-primary" href="{% url 'weather:documents' %}">Документация</a>
      </nav>
    </div>
    <div class="container mt-5">
        <div class="row">
            <div class="col-5 offset-1">
                <h1>Погода в вашем городе</h1>
                <form action="" method="post">
                    {% csrf_token %}
                    <label for="city">Город</label>
                    {{ form.name }}
                    <input type="submit" name="send" value="Узнать" class="mt-2 btn btn-secondary">
                </form>

            </div>
            <div class="col-4 offset-1">
                <h1>Информация</h1>


                {% for info in all_info %}
                <div class="alert alert-info">
                    <div class="row">
                        <div class="col-9">
                            <b>Город:</b> {{info.city}}<br>
                            <b>Температура:</b> {{info.temp}}<sup>o</sup><br>
                        </div>
                        <div class="col-2 offset-1">
                            <img src="http://openweathermap.org/img/w/{{ info.icon }}.png" alt="Фото погоды">
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

</body>
</html>

weather/templates/weather/info.html
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Погодное приложение</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
</head>
<body>
    <div class="d-flex flex-column flex-md-row align-items-center pb-2 mb-3 bg-white border-bottom shadow-sm">
      <a href="/" class="d-flex align-items-center link-body-emphasis text-decoration-none">
        <a class="me-3 ms-4 py-3 fs-4 link-body-emphasis text-decoration-none" href="#">Weather☁️</a>
      </a>

      <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
        <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'weather:index' %}">Главная</a>
        <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'weather:info' %}">Информация</a>
        <a class="me-3 btn btn-outline-primary" href="{% url 'weather:documents' %}">Документация</a>
      </nav>
    </div>
    <div>
        <h3>Информация о погоде</h1>
    </div>
</body>
</html>